[package]
name = "zeekstd"
version = "0.2.2"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive"] }
indicatif = "0.17.11"
zstd-safe = { version = "7.2.4", features = ["std", "seekable"] }
