[package]
name = "zeekstd_cli"
version = "0.2.3"
publish = false
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

[[bin]]
name = "zeekstd"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
indicatif = "0.17.11"
memmap2 = "0.9.5"
zeekstd = { path = "../lib" }
zstd-safe.workspace = true

[lints]
workspace = true
